apiVersion: v1
kind: pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html # nginx service path 
    - name: sidecar
      image: busybox
      command: ['sh', '-c', "echo 'Hello world' > /usr/share/nginx/html/index.html ; do sleep 3600; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
  volumes:
    - name: shared-data
      emptyDir: {}
