apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx-pod-svc # Add this label to match the Service selector
spec:
  containers:
    - name: nginx
      image: nginx:1.16
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-pod-svc # Matches the Pod label
  ports:
    - port: 80
      targetPort: 80
  type: NodePort
